config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"

  get "pages/home"
  
  resources :records

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
class Record < ApplicationRecord

    paginates_per 5

    validates :company_name, presence: true
    validates :email_id, presence: true, uniqueness: true
    validates :company_code, uniqueness: true
    validates :company_name, length: { minimum: 5}
    validates :company_code, length: { minimum: 5} 
    #  , format: { with: /\A[A-Za-z]{2}[0-9]{2}[EN]\z/, message: 'Length should be 5 characters, 1st & 2nd characters should be alphabets, 3rd & 4th characters should be numbers, 5th character should be E or N'}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  
  allow_browser versions: :modern

  before_action :authenticate_user!

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

      before_action :authenticate_user!

     def index    
        @records = Record.all.page(params[:page])
     end
 
     def new
       @record = Record.new
     end
 
     def create
       @record = Record.create(records_params)
       if @record.save
         redirect_to records_path
       else
         render:new
       end
     end
     
     def show
      @record = Record.find(params[:id])
     end
     
     def edit
        @record = Record.find(params[:id])
      # @record = Record.find(params.expect(:id))

     end
 
     def update
         @record = Record.find(params[:id])
      if @record = Record.update(records_params)
         redirect_to records_path
       else
         render:new
       end
     end
     def destroy
      @record = Record.find(params[:id])
      @record.destroy
         redirect_to records_path
     end
       
     private 
 
     def records_params

         params.require(:record).permit(:company_name, :email_id, :company_code, :strength, :website)
        
         # params.expect(company_record: [:company_name, :email_id, :company_code, :strength, :website ])

     end
 
 end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Company Record" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    
  <% if notice.present? %>
  <p class="notice alert alert-success"><%= notice %></p>
  <% end %>

  <% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="alert alert-primary" role="alert">
  This is a primary alert—check it out!
</div>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>

<div class="container" >
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="#">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/records/edit.html.erb
<h1> Edit Company Record </h1>

<%= form_with model: @record do |form| %>

     <% if @record.errors.any? %>
       <% @record.errors.full_messages.each do |message| %>
        <p> <%= message %> </p>
        <% end %>
     <% end %>

    <div>
    <%= form.label :company_name %><br>
    <%= form.text_field :company_name %>
    </div>

    <div>
    <%= form.label :email_id %><br>
    <%= form.email_field :email_id %>
    </div>

    <div>
    <%= form.label :company_code %><br>
    <%= form.text_field :company_code %>
    </div>

    <div>
    <%= form.label :strength %><br>
    <%= form.text_field :strength %>
    </div>

    <div>
    <%= form.label :website %><br>
    <%= form.text_field :website %>
    </div>

    <div>
    <%= form.submit %>
    </div>
    <% end %>

app/views/records/index.html.erb
<div class="card text-center">
<div class="container text-center">
  <div class="row align-items-start">
<h1>Company Records</h1>

<td> <%= link_to 'New Company Record', new_record_path %> </td>
<table class="table table-success table-striped">
<thead>
<tr>
<th> Company ID</th>
<th> Company Name</th>
<th> Email ID</th>
<th> Company Code </th>
<th> Strength </th>
<th> Website </th>
<th> Created Time </th>
<th colspan="3"> Action </th>
</tr>
</thead>
<tbody>
<% @records.each do |record| %>
    <tr>

       <td> <%= record.id %> </td>
       <td> <%= record.company_name %> </td>
       <td> <%= record.email_id %> </td>
       <td> <%= record.company_code%> </td>
       <td> <%= record.strength %> </td>
       <td> <%= record.website %> </td>
       <td> <%= record.created_at %></td>
       <td> <button type="button" class="btn btn-info "> <%= link_to 'View', record %> </button></td>
       <td> <button type="button" class="btn btn-light "> <%= link_to 'Edit', edit_record_path(record) %> </button> </td>
       <td> <%= button_to 'Delete', record, method: :delete, data: {confirm: 'Are you sure?'} %> </td>
    </tr>
<% end %>
</tbody>
</table >
<%= paginate @records %>
</div>
</div>
</div>

app/views/records/new.html.erb
<h1> New Company Record </h1>

<%= form_with model: @record do |form| %>
 
    <% if @record.errors.any? %>
    <% @record.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert">
       <p> <%= message %> </p>
      </div>
      <% end %>
    <% end %>   
   

    <div>
    <%= form.label :company_name %><br>
    <%= form.text_field :company_name %>
    </div>

    <div>
    <%= form.label :email_id %><br>
    <%= form.email_field :email_id %>
    </div>

    <div>
    <%= form.label :company_code %><br>
    <%= form.text_field :company_code %>
    </div>

    <div>
    <%= form.label :strength %><br>
    <%= form.text_field :strength %>
    </div>

    <div>
    <%= form.label :website %><br>
    <%= form.text_field :website %>
    </div>

    <div>
    <%= form.submit %>
    </div>
    <% end %>

app/views/records/show.html.erb
<h1> Company Record Details </h1>

<p><strong>Company Name: </strong><%= @record.company_name %></p>
<p><strong>Email ID: </strong><%= @record.email_id %></p>
<p><strong>Company code:</strong><%= @record.company_code %></p>
<p><strong>Strength: </strong><%= @record.strength %></p>
<p><strong>Website: </strong><%= @record.website %></p>
<p><strong>Created Time: </strong><%= @record.created_at %></p>

<td> <%= link_to 'Back', records_path %> </td> | <td> <%= link_to 'Edit', edit_record_path(@record) %> </td> |

<td> <%= link_to 'Delete', records_path, method: :delete, data: {confirm: 'Are you sure?'} %> </td>